version: "3.5"
networks:
  redstonenetwork:
    name: redstonenetwork

services:
 pmail-node:
    container_name: pmail-node
    image: baidang201/pmail-node:latest
    working_dir: /var/www/substrate
    volumes:
      - './pmaildata:/data'
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/substrate/.cargo
    command: /usr/local/bin/substrate --dev --base-path  /data --rpc-cors all --rpc-methods=unsafe --rpc-external --unsafe-ws-external --unsafe-rpc-external   --pruning archive
    restart: always

    networks:
      redstonenetwork:
        aliases: 
          - redstonenetwork
